### ISSUE TITLE
[Cliente] Solicita relatório de consumo

### ISSUE THREAD

**Issue by renasantini** [TreinaDev/gestao_interna#10]
Eu, cliente, gostaria de solicitar, via API, um relatório de consumo:

- Total de conversas no mês atual
- Total de mensagens no mês atual
- Previsão de valor a ser cobrado ao final do mês

Meses anteriores

- Total de conversas por mês
- Total de mensagens por mês

**Comment by renasantini** [comment]
Sistema deve fornecer ao sistema de vendas via API relatório com:

- Total de conversas no mês atual
- Total de mensagens no mês atual
- Previsão de valor a ser cobrado ao final do mês

Meses anteriores
- Total de conversas por mês
- Total de mensagens por mês

**Comment by librity** [comment]
PR: https://github.com/TreinaDev/gestao_interna/pull/42
