### ISSUE TITLE
Atualizar preço mensal de um plano

### ISSUE THREAD

**Issue by joaorsalmeida** [TreinaDev/gestao_interna#17]
Eu, um usuário autenticado do sistema, gostaria de atualizar o valor mensal de um plano para realizar as novas vendas por um novo preço. Ao atualizar este valor, deve ser registrado o valor antigo no histórico de preços do plano para garantir que não se perca a informação de todas mudanças de preço ao longo dos meses/anos.

**Comment by librity** [comment]
Solicitação de puxão: https://github.com/TreinaDev/gestao_interna/pull/29
