### ISSUE TITLE
Arrumar Teste de API dos planos

### ISSUE THREAD

**Issue by Guifs100** [TreinaDev/gestao_interna#24]
Teste de API passa apenas as informações de name e de price do plano

**Comment by librity** [comment]
Acredito que este PR resolve: https://github.com/TreinaDev/gestao_interna/pull/29
Testei e está retornando todos os dados.

![2020-06-29_17-13](https://user-images.githubusercontent.com/19496542/86051517-ec5b7c00-ba2b-11ea-8123-13914bd6f91c.png)

**Comment by librity** [comment]
Resolvido no PR: https://github.com/TreinaDev/gestao_interna/pull/29
