### ISSUE TITLE
Model de Empresa

### ISSUE THREAD

**Issue by librity** [TreinaDev/gestao_interna#6]
## Que
Gostaria de criar uma empresa com token no sistema para identificar todos os Bots que ela tenha.

## Como
- [ ]  Token único, de 6 dígitos, alfanumérico e todo maiúsculo.
- [ ]  Criar um Model de Empresa com campo de booleano de bloqueado, default: false

**Comment by joaorsalmeida** [comment]
Não me parece um card que entrega valor ao cliente final, o card de API de empresa me parece que pode incluir os dados desse card.
