### ISSUE TITLE
Recebendo informações dos bots

### ISSUE THREAD

**Issue by penhalver02** [TreinaDev/gestao_interna#9]
Eu gostaria que o sistema receba as informações dos bots para controle dos planos, e para verificar a quantidade de mensagens. Recebemos:

- quando começa uma conversa (dia e hora)
- id da conversa
- quando terminou
- quantidades de mensagem e conversas

**Comment by librity** [comment]
![2020-07-07_18-37](https://user-images.githubusercontent.com/19496542/86846143-e1829600-c080-11ea-84bd-5ddff887c43c.png)
